version: '3.8'

services:
  # Main ML Face Service
  ml-face-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: ml-face-service:latest
    container_name: ml-face-service
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SERVER_PORT=8080
      - MODEL_PATH=/app/models
    volumes:
      # Mount models directory for persistence
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G

# ================================
# Usage:
# ================================
#
# Build and run:
#   docker-compose up --build
#
# Run in background:
#   docker-compose up -d
#
# View logs:
#   docker-compose logs -f
#
# Stop service:
#   docker-compose down
#
# ================================
