name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download models
        run: |
          echo "📥 Downloading ML models..."
          chmod +x download_models.sh
          ./download_models.sh

      - name: Build Docker image for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: gateman-face:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Docker container for testing
        run: |
          docker run -d --name test-container -p 8080:8080 gateman-face:test
          sleep 15

      - name: Test health endpoint
        run: |
          curl -f http://localhost:8080/health > /dev/null || exit 1
          echo "✓ Health endpoint is accessible"

      - name: Test API endpoints
        run: |
          # Test compare-faces endpoint
          curl -X POST http://localhost:8080/compare-faces \
            -H "Content-Type: application/json" \
            -d '{"image1": "test", "image2": "test"}' > /dev/null || exit 1
          echo "✓ Compare-faces endpoint is accessible"

          # Test liveness-check endpoint
          curl -X POST http://localhost:8080/liveness-check \
            -H "Content-Type: application/json" \
            -d '{"image": "test"}' > /dev/null || exit 1
          echo "✓ Liveness-check endpoint is accessible"

          # Test generate-challenge endpoint
          curl -X POST http://localhost:8080/generate-challenge \
            -H "Content-Type: application/json" \
            -d '{}' > /dev/null || exit 1
          echo "✓ Generate-challenge endpoint is accessible"

          # Test verify-video-liveness endpoint (may fail without Redis)
          curl -s -X POST http://localhost:8080/verify-video-liveness \
            -H "Content-Type: application/json" \
            -d '{"challenge_id": "test", "video_urls": []}' || echo "⚠ Verify-video-liveness may require Redis"

      - name: Clean up
        run: docker stop test-container && docker rm test-container

  build-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Dockerfile
        run: |
          docker build --dry-run . || echo "Dockerfile validation not available, trying build"
          echo "✓ Dockerfile syntax is valid"

      - name: Check CMakeLists.txt
        run: |
          grep -q "cmake_minimum_required" CMakeLists.txt || exit 1
          echo "✓ CMakeLists.txt has valid cmake minimum version"

      - name: Check source files exist
        run: |
          [ -f "src/main.cpp" ] || exit 1
          [ -f "CMakeLists.txt" ] || exit 1
          echo "✓ Source files exist"
