name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (optional, defaults to commit SHA)'
        required: false
        type: string

env:
  REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
  PROJECT_NAME: gateman-face
  IMAGE_NAME: face-service-prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Download models (if needed)
        run: |
          echo "📥 Ensuring models are available..."
          if [ ! -f "models/dlib_face_recognition_resnet_model_v1.dat" ]; then
            echo "Downloading face recognition model..."
            wget -O models/dlib_face_recognition_resnet_model_v1.dat \
              "http://dlib.net/files/dlib_face_recognition_resnet_model_v1.dat.bz2" \
              && bunzip2 models/dlib_face_recognition_resnet_model_v1.dat.bz2 \
              || echo "Warning: Could not download face recognition model"
          fi
          if [ ! -f "models/shape_predictor_68_face_landmarks.dat" ]; then
            echo "Downloading face landmarks model..."
            wget -O models/shape_predictor_68_face_landmarks.dat \
              "http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2" \
              && bunzip2 models/shape_predictor_68_face_landmarks.dat.bz2 \
              || echo "Warning: Could not download face landmarks model"
          fi

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROJECT_NAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event.inputs.tag != '' }}

      - name: Test Docker build locally
        run: |
          echo "🧪 Testing production Docker build..."
          docker build -f Dockerfile.prod -t test-build . --progress=plain
          echo "✅ Production Docker build test successful"

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: true
          sbom: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.PROJECT_NAME }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true